[theme]
base = "light"
primaryColor = "#FF9900"
backgroundColor = "#F3F4F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F1111"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"